apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::980745618099:role/dsd-prod-devops
      groups:
        - system:masters 
    - rolearn: arn:aws:iam::980745618099:role/dsd-prod-workers-NodeInstanceRole-X6A14AD7LMOF
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:nodes
        - system:bootstrappers
  mapUsers: |
    - userarn: arn:aws:iam::155210401989:user/nsaraiya-infomagnus
      username: nsaraiya-infomagnus
      groups:
        - system:masters
    - userarn: arn:aws:iam::155210401989:user/ChristianNichols
      username: ChristianNichols
      groups:
        - system:masters

