apiVersion: v1
kind: Service
metadata:
  name: smartorder-service
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app: smartorder
    
