FROM python:3.7

RUN mkdir -p /var/www/dsdp

# Update working directory
WORKDIR /var/www/dsdp

COPY requirements.txt ./requirements.txt
COPY requirements-dev.txt ./requirements-dev.txt

# Install explicitly because of  segment fault with psycopg2.
RUN pip3 install --no-binary :all: psycopg2

# Install the Python libraries
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install --no-cache-dir -r requirements-dev.txt

# copy everything from this directory to server/flask docker container
COPY . /var/www/dsdp/

RUN echo "CONFIG_PATH: $CONFIG_PATH"
