import enum

FINAL_NOTIFICATION_ID = 0


class PredictionStatus(enum.Enum):
    CREATED = "CREATED"
    IN_PROGRESS = "IN_PROGRESS"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"
    IN_REVIEW = "IN_REVIEW"


class WorkOrderStatus(enum.Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    SENT_TO_FEEDER = "SENT_TO_FEEDER"
    DENORMALIZATION_IN_PROGRESS = "DENORMALIZATION_IN_PROGRESS"
    DENORMALIZATION_SUCCESS = "DENORMALIZATION_SUCCESS"
    DENORMALIZATION_FAILED = "DENORMALIZATION_FAILED"
    SENT_TO_PREDICTION = "SENT_TO_PREDICTION"
    PREDICTION_IN_PROGRESS = "PREDICTION_IN_PROGRESS"
    PREDICTION_SUCCESS = "PREDICTION_SUCCESS"
    PREDICTION_FAILED = "PREDICTION_FAILED"


class NotificationType(enum.Enum):
    DISTRIBUTOR = "DISTRIBUTOR"
    RETAILER = "RETAILER"
    FINAL = "FINAL"


class NotificationStatus(enum.Enum):
    LOADED = "LOADED"
    NEW = "NEW"
    FAILED = "FAILED"


scan_source_lookup = {31: "FD Load", 24: "1010 Load"}
